// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.12
// source: scraper.proto

package trend_scratcher

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ControlRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Action:
	//
	//	*ControlRequest_EmulateViewport
	//	*ControlRequest_Navigate
	//	*ControlRequest_Sleep
	//	*ControlRequest_Click
	//	*ControlRequest_SendKeys
	//	*ControlRequest_CaptureHtml
	//	*ControlRequest_CaptureScreenshot
	//	*ControlRequest_WaitVisible
	//	*ControlRequest_ScrollBy
	Action isControlRequest_Action `protobuf_oneof:"action"`
}

func (x *ControlRequest) Reset() {
	*x = ControlRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_scraper_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ControlRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ControlRequest) ProtoMessage() {}

func (x *ControlRequest) ProtoReflect() protoreflect.Message {
	mi := &file_scraper_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ControlRequest.ProtoReflect.Descriptor instead.
func (*ControlRequest) Descriptor() ([]byte, []int) {
	return file_scraper_proto_rawDescGZIP(), []int{0}
}

func (m *ControlRequest) GetAction() isControlRequest_Action {
	if m != nil {
		return m.Action
	}
	return nil
}

func (x *ControlRequest) GetEmulateViewport() *CA_EmulateViewport {
	if x, ok := x.GetAction().(*ControlRequest_EmulateViewport); ok {
		return x.EmulateViewport
	}
	return nil
}

func (x *ControlRequest) GetNavigate() *CA_Navigate {
	if x, ok := x.GetAction().(*ControlRequest_Navigate); ok {
		return x.Navigate
	}
	return nil
}

func (x *ControlRequest) GetSleep() *CA_Sleep {
	if x, ok := x.GetAction().(*ControlRequest_Sleep); ok {
		return x.Sleep
	}
	return nil
}

func (x *ControlRequest) GetClick() *CA_Click {
	if x, ok := x.GetAction().(*ControlRequest_Click); ok {
		return x.Click
	}
	return nil
}

func (x *ControlRequest) GetSendKeys() *CA_SendKeys {
	if x, ok := x.GetAction().(*ControlRequest_SendKeys); ok {
		return x.SendKeys
	}
	return nil
}

func (x *ControlRequest) GetCaptureHtml() *CA_CaptureHtml {
	if x, ok := x.GetAction().(*ControlRequest_CaptureHtml); ok {
		return x.CaptureHtml
	}
	return nil
}

func (x *ControlRequest) GetCaptureScreenshot() *CA_CaptureScreenshot {
	if x, ok := x.GetAction().(*ControlRequest_CaptureScreenshot); ok {
		return x.CaptureScreenshot
	}
	return nil
}

func (x *ControlRequest) GetWaitVisible() *CA_WaitVisible {
	if x, ok := x.GetAction().(*ControlRequest_WaitVisible); ok {
		return x.WaitVisible
	}
	return nil
}

func (x *ControlRequest) GetScrollBy() *CA_ScrollBy {
	if x, ok := x.GetAction().(*ControlRequest_ScrollBy); ok {
		return x.ScrollBy
	}
	return nil
}

type isControlRequest_Action interface {
	isControlRequest_Action()
}

type ControlRequest_EmulateViewport struct {
	EmulateViewport *CA_EmulateViewport `protobuf:"bytes,1,opt,name=emulateViewport,proto3,oneof"`
}

type ControlRequest_Navigate struct {
	Navigate *CA_Navigate `protobuf:"bytes,2,opt,name=navigate,proto3,oneof"`
}

type ControlRequest_Sleep struct {
	Sleep *CA_Sleep `protobuf:"bytes,3,opt,name=sleep,proto3,oneof"`
}

type ControlRequest_Click struct {
	Click *CA_Click `protobuf:"bytes,4,opt,name=click,proto3,oneof"`
}

type ControlRequest_SendKeys struct {
	SendKeys *CA_SendKeys `protobuf:"bytes,5,opt,name=sendKeys,proto3,oneof"`
}

type ControlRequest_CaptureHtml struct {
	CaptureHtml *CA_CaptureHtml `protobuf:"bytes,6,opt,name=captureHtml,proto3,oneof"`
}

type ControlRequest_CaptureScreenshot struct {
	CaptureScreenshot *CA_CaptureScreenshot `protobuf:"bytes,7,opt,name=captureScreenshot,proto3,oneof"`
}

type ControlRequest_WaitVisible struct {
	WaitVisible *CA_WaitVisible `protobuf:"bytes,8,opt,name=waitVisible,proto3,oneof"`
}

type ControlRequest_ScrollBy struct {
	ScrollBy *CA_ScrollBy `protobuf:"bytes,9,opt,name=scrollBy,proto3,oneof"`
}

func (*ControlRequest_EmulateViewport) isControlRequest_Action() {}

func (*ControlRequest_Navigate) isControlRequest_Action() {}

func (*ControlRequest_Sleep) isControlRequest_Action() {}

func (*ControlRequest_Click) isControlRequest_Action() {}

func (*ControlRequest_SendKeys) isControlRequest_Action() {}

func (*ControlRequest_CaptureHtml) isControlRequest_Action() {}

func (*ControlRequest_CaptureScreenshot) isControlRequest_Action() {}

func (*ControlRequest_WaitVisible) isControlRequest_Action() {}

func (*ControlRequest_ScrollBy) isControlRequest_Action() {}

type ControlResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Payload:
	//
	//	*ControlResponse_Screenshot
	//	*ControlResponse_Html
	//	*ControlResponse_Error
	Payload isControlResponse_Payload `protobuf_oneof:"payload"`
}

func (x *ControlResponse) Reset() {
	*x = ControlResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_scraper_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ControlResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ControlResponse) ProtoMessage() {}

func (x *ControlResponse) ProtoReflect() protoreflect.Message {
	mi := &file_scraper_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ControlResponse.ProtoReflect.Descriptor instead.
func (*ControlResponse) Descriptor() ([]byte, []int) {
	return file_scraper_proto_rawDescGZIP(), []int{1}
}

func (m *ControlResponse) GetPayload() isControlResponse_Payload {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (x *ControlResponse) GetScreenshot() *CA_CaptureScreenshot_Response {
	if x, ok := x.GetPayload().(*ControlResponse_Screenshot); ok {
		return x.Screenshot
	}
	return nil
}

func (x *ControlResponse) GetHtml() *CA_CaptureHtml_Response {
	if x, ok := x.GetPayload().(*ControlResponse_Html); ok {
		return x.Html
	}
	return nil
}

func (x *ControlResponse) GetError() *CA_Error_Response {
	if x, ok := x.GetPayload().(*ControlResponse_Error); ok {
		return x.Error
	}
	return nil
}

type isControlResponse_Payload interface {
	isControlResponse_Payload()
}

type ControlResponse_Screenshot struct {
	Screenshot *CA_CaptureScreenshot_Response `protobuf:"bytes,1,opt,name=screenshot,proto3,oneof"`
}

type ControlResponse_Html struct {
	Html *CA_CaptureHtml_Response `protobuf:"bytes,2,opt,name=html,proto3,oneof"`
}

type ControlResponse_Error struct {
	Error *CA_Error_Response `protobuf:"bytes,3,opt,name=error,proto3,oneof"`
}

func (*ControlResponse_Screenshot) isControlResponse_Payload() {}

func (*ControlResponse_Html) isControlResponse_Payload() {}

func (*ControlResponse_Error) isControlResponse_Payload() {}

type CA_EmulateViewport struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Width  int64 `protobuf:"varint,1,opt,name=width,proto3" json:"width,omitempty"`
	Height int64 `protobuf:"varint,2,opt,name=height,proto3" json:"height,omitempty"`
}

func (x *CA_EmulateViewport) Reset() {
	*x = CA_EmulateViewport{}
	if protoimpl.UnsafeEnabled {
		mi := &file_scraper_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CA_EmulateViewport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CA_EmulateViewport) ProtoMessage() {}

func (x *CA_EmulateViewport) ProtoReflect() protoreflect.Message {
	mi := &file_scraper_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CA_EmulateViewport.ProtoReflect.Descriptor instead.
func (*CA_EmulateViewport) Descriptor() ([]byte, []int) {
	return file_scraper_proto_rawDescGZIP(), []int{2}
}

func (x *CA_EmulateViewport) GetWidth() int64 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *CA_EmulateViewport) GetHeight() int64 {
	if x != nil {
		return x.Height
	}
	return 0
}

type CA_Navigate struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Url string `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
}

func (x *CA_Navigate) Reset() {
	*x = CA_Navigate{}
	if protoimpl.UnsafeEnabled {
		mi := &file_scraper_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CA_Navigate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CA_Navigate) ProtoMessage() {}

func (x *CA_Navigate) ProtoReflect() protoreflect.Message {
	mi := &file_scraper_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CA_Navigate.ProtoReflect.Descriptor instead.
func (*CA_Navigate) Descriptor() ([]byte, []int) {
	return file_scraper_proto_rawDescGZIP(), []int{3}
}

func (x *CA_Navigate) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type CA_Sleep struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Duration int64 `protobuf:"varint,1,opt,name=duration,proto3" json:"duration,omitempty"`
}

func (x *CA_Sleep) Reset() {
	*x = CA_Sleep{}
	if protoimpl.UnsafeEnabled {
		mi := &file_scraper_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CA_Sleep) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CA_Sleep) ProtoMessage() {}

func (x *CA_Sleep) ProtoReflect() protoreflect.Message {
	mi := &file_scraper_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CA_Sleep.ProtoReflect.Descriptor instead.
func (*CA_Sleep) Descriptor() ([]byte, []int) {
	return file_scraper_proto_rawDescGZIP(), []int{4}
}

func (x *CA_Sleep) GetDuration() int64 {
	if x != nil {
		return x.Duration
	}
	return 0
}

type CA_Click struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Selector string `protobuf:"bytes,1,opt,name=selector,proto3" json:"selector,omitempty"`
}

func (x *CA_Click) Reset() {
	*x = CA_Click{}
	if protoimpl.UnsafeEnabled {
		mi := &file_scraper_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CA_Click) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CA_Click) ProtoMessage() {}

func (x *CA_Click) ProtoReflect() protoreflect.Message {
	mi := &file_scraper_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CA_Click.ProtoReflect.Descriptor instead.
func (*CA_Click) Descriptor() ([]byte, []int) {
	return file_scraper_proto_rawDescGZIP(), []int{5}
}

func (x *CA_Click) GetSelector() string {
	if x != nil {
		return x.Selector
	}
	return ""
}

type CA_SendKeys struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Selector string `protobuf:"bytes,1,opt,name=selector,proto3" json:"selector,omitempty"`
	Input    string `protobuf:"bytes,2,opt,name=input,proto3" json:"input,omitempty"`
}

func (x *CA_SendKeys) Reset() {
	*x = CA_SendKeys{}
	if protoimpl.UnsafeEnabled {
		mi := &file_scraper_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CA_SendKeys) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CA_SendKeys) ProtoMessage() {}

func (x *CA_SendKeys) ProtoReflect() protoreflect.Message {
	mi := &file_scraper_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CA_SendKeys.ProtoReflect.Descriptor instead.
func (*CA_SendKeys) Descriptor() ([]byte, []int) {
	return file_scraper_proto_rawDescGZIP(), []int{6}
}

func (x *CA_SendKeys) GetSelector() string {
	if x != nil {
		return x.Selector
	}
	return ""
}

func (x *CA_SendKeys) GetInput() string {
	if x != nil {
		return x.Input
	}
	return ""
}

type CA_CaptureScreenshot struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CA_CaptureScreenshot) Reset() {
	*x = CA_CaptureScreenshot{}
	if protoimpl.UnsafeEnabled {
		mi := &file_scraper_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CA_CaptureScreenshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CA_CaptureScreenshot) ProtoMessage() {}

func (x *CA_CaptureScreenshot) ProtoReflect() protoreflect.Message {
	mi := &file_scraper_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CA_CaptureScreenshot.ProtoReflect.Descriptor instead.
func (*CA_CaptureScreenshot) Descriptor() ([]byte, []int) {
	return file_scraper_proto_rawDescGZIP(), []int{7}
}

type CA_CaptureScreenshot_Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Img []byte `protobuf:"bytes,1,opt,name=img,proto3" json:"img,omitempty"`
}

func (x *CA_CaptureScreenshot_Response) Reset() {
	*x = CA_CaptureScreenshot_Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_scraper_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CA_CaptureScreenshot_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CA_CaptureScreenshot_Response) ProtoMessage() {}

func (x *CA_CaptureScreenshot_Response) ProtoReflect() protoreflect.Message {
	mi := &file_scraper_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CA_CaptureScreenshot_Response.ProtoReflect.Descriptor instead.
func (*CA_CaptureScreenshot_Response) Descriptor() ([]byte, []int) {
	return file_scraper_proto_rawDescGZIP(), []int{8}
}

func (x *CA_CaptureScreenshot_Response) GetImg() []byte {
	if x != nil {
		return x.Img
	}
	return nil
}

type CA_CaptureHtml struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CA_CaptureHtml) Reset() {
	*x = CA_CaptureHtml{}
	if protoimpl.UnsafeEnabled {
		mi := &file_scraper_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CA_CaptureHtml) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CA_CaptureHtml) ProtoMessage() {}

func (x *CA_CaptureHtml) ProtoReflect() protoreflect.Message {
	mi := &file_scraper_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CA_CaptureHtml.ProtoReflect.Descriptor instead.
func (*CA_CaptureHtml) Descriptor() ([]byte, []int) {
	return file_scraper_proto_rawDescGZIP(), []int{9}
}

type CA_CaptureHtml_Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Html string `protobuf:"bytes,1,opt,name=html,proto3" json:"html,omitempty"`
}

func (x *CA_CaptureHtml_Response) Reset() {
	*x = CA_CaptureHtml_Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_scraper_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CA_CaptureHtml_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CA_CaptureHtml_Response) ProtoMessage() {}

func (x *CA_CaptureHtml_Response) ProtoReflect() protoreflect.Message {
	mi := &file_scraper_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CA_CaptureHtml_Response.ProtoReflect.Descriptor instead.
func (*CA_CaptureHtml_Response) Descriptor() ([]byte, []int) {
	return file_scraper_proto_rawDescGZIP(), []int{10}
}

func (x *CA_CaptureHtml_Response) GetHtml() string {
	if x != nil {
		return x.Html
	}
	return ""
}

type CA_Error_Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Error string `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *CA_Error_Response) Reset() {
	*x = CA_Error_Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_scraper_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CA_Error_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CA_Error_Response) ProtoMessage() {}

func (x *CA_Error_Response) ProtoReflect() protoreflect.Message {
	mi := &file_scraper_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CA_Error_Response.ProtoReflect.Descriptor instead.
func (*CA_Error_Response) Descriptor() ([]byte, []int) {
	return file_scraper_proto_rawDescGZIP(), []int{11}
}

func (x *CA_Error_Response) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type CA_WaitVisible struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Selector string `protobuf:"bytes,1,opt,name=selector,proto3" json:"selector,omitempty"`
}

func (x *CA_WaitVisible) Reset() {
	*x = CA_WaitVisible{}
	if protoimpl.UnsafeEnabled {
		mi := &file_scraper_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CA_WaitVisible) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CA_WaitVisible) ProtoMessage() {}

func (x *CA_WaitVisible) ProtoReflect() protoreflect.Message {
	mi := &file_scraper_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CA_WaitVisible.ProtoReflect.Descriptor instead.
func (*CA_WaitVisible) Descriptor() ([]byte, []int) {
	return file_scraper_proto_rawDescGZIP(), []int{12}
}

func (x *CA_WaitVisible) GetSelector() string {
	if x != nil {
		return x.Selector
	}
	return ""
}

type CA_ScrollBy struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ScrollBy int64 `protobuf:"varint,1,opt,name=scrollBy,proto3" json:"scrollBy,omitempty"`
}

func (x *CA_ScrollBy) Reset() {
	*x = CA_ScrollBy{}
	if protoimpl.UnsafeEnabled {
		mi := &file_scraper_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CA_ScrollBy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CA_ScrollBy) ProtoMessage() {}

func (x *CA_ScrollBy) ProtoReflect() protoreflect.Message {
	mi := &file_scraper_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CA_ScrollBy.ProtoReflect.Descriptor instead.
func (*CA_ScrollBy) Descriptor() ([]byte, []int) {
	return file_scraper_proto_rawDescGZIP(), []int{13}
}

func (x *CA_ScrollBy) GetScrollBy() int64 {
	if x != nil {
		return x.ScrollBy
	}
	return 0
}

var File_scraper_proto protoreflect.FileDescriptor

var file_scraper_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x73, 0x63, 0x72, 0x61, 0x70, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x07, 0x73, 0x63, 0x72, 0x61, 0x70, 0x65, 0x72, 0x22, 0x9e, 0x04, 0x0a, 0x0e, 0x43, 0x6f, 0x6e,
	0x74, 0x72, 0x6f, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x47, 0x0a, 0x0f, 0x65,
	0x6d, 0x75, 0x6c, 0x61, 0x74, 0x65, 0x56, 0x69, 0x65, 0x77, 0x70, 0x6f, 0x72, 0x74, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x73, 0x63, 0x72, 0x61, 0x70, 0x65, 0x72, 0x2e, 0x43,
	0x41, 0x5f, 0x45, 0x6d, 0x75, 0x6c, 0x61, 0x74, 0x65, 0x56, 0x69, 0x65, 0x77, 0x70, 0x6f, 0x72,
	0x74, 0x48, 0x00, 0x52, 0x0f, 0x65, 0x6d, 0x75, 0x6c, 0x61, 0x74, 0x65, 0x56, 0x69, 0x65, 0x77,
	0x70, 0x6f, 0x72, 0x74, 0x12, 0x32, 0x0a, 0x08, 0x6e, 0x61, 0x76, 0x69, 0x67, 0x61, 0x74, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x73, 0x63, 0x72, 0x61, 0x70, 0x65, 0x72,
	0x2e, 0x43, 0x41, 0x5f, 0x4e, 0x61, 0x76, 0x69, 0x67, 0x61, 0x74, 0x65, 0x48, 0x00, 0x52, 0x08,
	0x6e, 0x61, 0x76, 0x69, 0x67, 0x61, 0x74, 0x65, 0x12, 0x29, 0x0a, 0x05, 0x73, 0x6c, 0x65, 0x65,
	0x70, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x73, 0x63, 0x72, 0x61, 0x70, 0x65,
	0x72, 0x2e, 0x43, 0x41, 0x5f, 0x53, 0x6c, 0x65, 0x65, 0x70, 0x48, 0x00, 0x52, 0x05, 0x73, 0x6c,
	0x65, 0x65, 0x70, 0x12, 0x29, 0x0a, 0x05, 0x63, 0x6c, 0x69, 0x63, 0x6b, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x11, 0x2e, 0x73, 0x63, 0x72, 0x61, 0x70, 0x65, 0x72, 0x2e, 0x43, 0x41, 0x5f,
	0x43, 0x6c, 0x69, 0x63, 0x6b, 0x48, 0x00, 0x52, 0x05, 0x63, 0x6c, 0x69, 0x63, 0x6b, 0x12, 0x32,
	0x0a, 0x08, 0x73, 0x65, 0x6e, 0x64, 0x4b, 0x65, 0x79, 0x73, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x14, 0x2e, 0x73, 0x63, 0x72, 0x61, 0x70, 0x65, 0x72, 0x2e, 0x43, 0x41, 0x5f, 0x53, 0x65,
	0x6e, 0x64, 0x4b, 0x65, 0x79, 0x73, 0x48, 0x00, 0x52, 0x08, 0x73, 0x65, 0x6e, 0x64, 0x4b, 0x65,
	0x79, 0x73, 0x12, 0x3b, 0x0a, 0x0b, 0x63, 0x61, 0x70, 0x74, 0x75, 0x72, 0x65, 0x48, 0x74, 0x6d,
	0x6c, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x73, 0x63, 0x72, 0x61, 0x70, 0x65,
	0x72, 0x2e, 0x43, 0x41, 0x5f, 0x43, 0x61, 0x70, 0x74, 0x75, 0x72, 0x65, 0x48, 0x74, 0x6d, 0x6c,
	0x48, 0x00, 0x52, 0x0b, 0x63, 0x61, 0x70, 0x74, 0x75, 0x72, 0x65, 0x48, 0x74, 0x6d, 0x6c, 0x12,
	0x4d, 0x0a, 0x11, 0x63, 0x61, 0x70, 0x74, 0x75, 0x72, 0x65, 0x53, 0x63, 0x72, 0x65, 0x65, 0x6e,
	0x73, 0x68, 0x6f, 0x74, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x73, 0x63, 0x72,
	0x61, 0x70, 0x65, 0x72, 0x2e, 0x43, 0x41, 0x5f, 0x43, 0x61, 0x70, 0x74, 0x75, 0x72, 0x65, 0x53,
	0x63, 0x72, 0x65, 0x65, 0x6e, 0x73, 0x68, 0x6f, 0x74, 0x48, 0x00, 0x52, 0x11, 0x63, 0x61, 0x70,
	0x74, 0x75, 0x72, 0x65, 0x53, 0x63, 0x72, 0x65, 0x65, 0x6e, 0x73, 0x68, 0x6f, 0x74, 0x12, 0x3b,
	0x0a, 0x0b, 0x77, 0x61, 0x69, 0x74, 0x56, 0x69, 0x73, 0x69, 0x62, 0x6c, 0x65, 0x18, 0x08, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x73, 0x63, 0x72, 0x61, 0x70, 0x65, 0x72, 0x2e, 0x43, 0x41,
	0x5f, 0x57, 0x61, 0x69, 0x74, 0x56, 0x69, 0x73, 0x69, 0x62, 0x6c, 0x65, 0x48, 0x00, 0x52, 0x0b,
	0x77, 0x61, 0x69, 0x74, 0x56, 0x69, 0x73, 0x69, 0x62, 0x6c, 0x65, 0x12, 0x32, 0x0a, 0x08, 0x73,
	0x63, 0x72, 0x6f, 0x6c, 0x6c, 0x42, 0x79, 0x18, 0x09, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e,
	0x73, 0x63, 0x72, 0x61, 0x70, 0x65, 0x72, 0x2e, 0x43, 0x41, 0x5f, 0x53, 0x63, 0x72, 0x6f, 0x6c,
	0x6c, 0x42, 0x79, 0x48, 0x00, 0x52, 0x08, 0x73, 0x63, 0x72, 0x6f, 0x6c, 0x6c, 0x42, 0x79, 0x42,
	0x08, 0x0a, 0x06, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0xd2, 0x01, 0x0a, 0x0f, 0x43, 0x6f,
	0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x48, 0x0a,
	0x0a, 0x73, 0x63, 0x72, 0x65, 0x65, 0x6e, 0x73, 0x68, 0x6f, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x26, 0x2e, 0x73, 0x63, 0x72, 0x61, 0x70, 0x65, 0x72, 0x2e, 0x43, 0x41, 0x5f, 0x43,
	0x61, 0x70, 0x74, 0x75, 0x72, 0x65, 0x53, 0x63, 0x72, 0x65, 0x65, 0x6e, 0x73, 0x68, 0x6f, 0x74,
	0x5f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x48, 0x00, 0x52, 0x0a, 0x73, 0x63, 0x72,
	0x65, 0x65, 0x6e, 0x73, 0x68, 0x6f, 0x74, 0x12, 0x36, 0x0a, 0x04, 0x68, 0x74, 0x6d, 0x6c, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x20, 0x2e, 0x73, 0x63, 0x72, 0x61, 0x70, 0x65, 0x72, 0x2e,
	0x43, 0x41, 0x5f, 0x43, 0x61, 0x70, 0x74, 0x75, 0x72, 0x65, 0x48, 0x74, 0x6d, 0x6c, 0x5f, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x48, 0x00, 0x52, 0x04, 0x68, 0x74, 0x6d, 0x6c, 0x12,
	0x32, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a,
	0x2e, 0x73, 0x63, 0x72, 0x61, 0x70, 0x65, 0x72, 0x2e, 0x43, 0x41, 0x5f, 0x45, 0x72, 0x72, 0x6f,
	0x72, 0x5f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x48, 0x00, 0x52, 0x05, 0x65, 0x72,
	0x72, 0x6f, 0x72, 0x42, 0x09, 0x0a, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x22, 0x42,
	0x0a, 0x12, 0x43, 0x41, 0x5f, 0x45, 0x6d, 0x75, 0x6c, 0x61, 0x74, 0x65, 0x56, 0x69, 0x65, 0x77,
	0x70, 0x6f, 0x72, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x77, 0x69, 0x64, 0x74, 0x68, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x05, 0x77, 0x69, 0x64, 0x74, 0x68, 0x12, 0x16, 0x0a, 0x06, 0x68, 0x65,
	0x69, 0x67, 0x68, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x68, 0x65, 0x69, 0x67,
	0x68, 0x74, 0x22, 0x1f, 0x0a, 0x0b, 0x43, 0x41, 0x5f, 0x4e, 0x61, 0x76, 0x69, 0x67, 0x61, 0x74,
	0x65, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x72, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03,
	0x75, 0x72, 0x6c, 0x22, 0x26, 0x0a, 0x08, 0x43, 0x41, 0x5f, 0x53, 0x6c, 0x65, 0x65, 0x70, 0x12,
	0x1a, 0x0a, 0x08, 0x64, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x08, 0x64, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x26, 0x0a, 0x08, 0x43,
	0x41, 0x5f, 0x43, 0x6c, 0x69, 0x63, 0x6b, 0x12, 0x1a, 0x0a, 0x08, 0x73, 0x65, 0x6c, 0x65, 0x63,
	0x74, 0x6f, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x73, 0x65, 0x6c, 0x65, 0x63,
	0x74, 0x6f, 0x72, 0x22, 0x3f, 0x0a, 0x0b, 0x43, 0x41, 0x5f, 0x53, 0x65, 0x6e, 0x64, 0x4b, 0x65,
	0x79, 0x73, 0x12, 0x1a, 0x0a, 0x08, 0x73, 0x65, 0x6c, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x73, 0x65, 0x6c, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x12, 0x14,
	0x0a, 0x05, 0x69, 0x6e, 0x70, 0x75, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x69,
	0x6e, 0x70, 0x75, 0x74, 0x22, 0x16, 0x0a, 0x14, 0x43, 0x41, 0x5f, 0x43, 0x61, 0x70, 0x74, 0x75,
	0x72, 0x65, 0x53, 0x63, 0x72, 0x65, 0x65, 0x6e, 0x73, 0x68, 0x6f, 0x74, 0x22, 0x31, 0x0a, 0x1d,
	0x43, 0x41, 0x5f, 0x43, 0x61, 0x70, 0x74, 0x75, 0x72, 0x65, 0x53, 0x63, 0x72, 0x65, 0x65, 0x6e,
	0x73, 0x68, 0x6f, 0x74, 0x5f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x10, 0x0a,
	0x03, 0x69, 0x6d, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x03, 0x69, 0x6d, 0x67, 0x22,
	0x10, 0x0a, 0x0e, 0x43, 0x41, 0x5f, 0x43, 0x61, 0x70, 0x74, 0x75, 0x72, 0x65, 0x48, 0x74, 0x6d,
	0x6c, 0x22, 0x2d, 0x0a, 0x17, 0x43, 0x41, 0x5f, 0x43, 0x61, 0x70, 0x74, 0x75, 0x72, 0x65, 0x48,
	0x74, 0x6d, 0x6c, 0x5f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04,
	0x68, 0x74, 0x6d, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x68, 0x74, 0x6d, 0x6c,
	0x22, 0x29, 0x0a, 0x11, 0x43, 0x41, 0x5f, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x5f, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x22, 0x2c, 0x0a, 0x0e, 0x43,
	0x41, 0x5f, 0x57, 0x61, 0x69, 0x74, 0x56, 0x69, 0x73, 0x69, 0x62, 0x6c, 0x65, 0x12, 0x1a, 0x0a,
	0x08, 0x73, 0x65, 0x6c, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x08, 0x73, 0x65, 0x6c, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x22, 0x29, 0x0a, 0x0b, 0x43, 0x41, 0x5f,
	0x53, 0x63, 0x72, 0x6f, 0x6c, 0x6c, 0x42, 0x79, 0x12, 0x1a, 0x0a, 0x08, 0x73, 0x63, 0x72, 0x6f,
	0x6c, 0x6c, 0x42, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x73, 0x63, 0x72, 0x6f,
	0x6c, 0x6c, 0x42, 0x79, 0x32, 0x4d, 0x0a, 0x07, 0x53, 0x63, 0x72, 0x61, 0x70, 0x65, 0x72, 0x12,
	0x42, 0x0a, 0x07, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x12, 0x17, 0x2e, 0x73, 0x63, 0x72,
	0x61, 0x70, 0x65, 0x72, 0x2e, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x18, 0x2e, 0x73, 0x63, 0x72, 0x61, 0x70, 0x65, 0x72, 0x2e, 0x43, 0x6f,
	0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x28,
	0x01, 0x30, 0x01, 0x42, 0x25, 0x5a, 0x23, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f,
	0x6d, 0x2f, 0x6d, 0x34, 0x73, 0x63, 0x68, 0x69, 0x6e, 0x69, 0x2f, 0x74, 0x72, 0x65, 0x6e, 0x64,
	0x2d, 0x73, 0x63, 0x72, 0x61, 0x74, 0x63, 0x68, 0x65, 0x72, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_scraper_proto_rawDescOnce sync.Once
	file_scraper_proto_rawDescData = file_scraper_proto_rawDesc
)

func file_scraper_proto_rawDescGZIP() []byte {
	file_scraper_proto_rawDescOnce.Do(func() {
		file_scraper_proto_rawDescData = protoimpl.X.CompressGZIP(file_scraper_proto_rawDescData)
	})
	return file_scraper_proto_rawDescData
}

var file_scraper_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_scraper_proto_goTypes = []interface{}{
	(*ControlRequest)(nil),                // 0: scraper.ControlRequest
	(*ControlResponse)(nil),               // 1: scraper.ControlResponse
	(*CA_EmulateViewport)(nil),            // 2: scraper.CA_EmulateViewport
	(*CA_Navigate)(nil),                   // 3: scraper.CA_Navigate
	(*CA_Sleep)(nil),                      // 4: scraper.CA_Sleep
	(*CA_Click)(nil),                      // 5: scraper.CA_Click
	(*CA_SendKeys)(nil),                   // 6: scraper.CA_SendKeys
	(*CA_CaptureScreenshot)(nil),          // 7: scraper.CA_CaptureScreenshot
	(*CA_CaptureScreenshot_Response)(nil), // 8: scraper.CA_CaptureScreenshot_Response
	(*CA_CaptureHtml)(nil),                // 9: scraper.CA_CaptureHtml
	(*CA_CaptureHtml_Response)(nil),       // 10: scraper.CA_CaptureHtml_Response
	(*CA_Error_Response)(nil),             // 11: scraper.CA_Error_Response
	(*CA_WaitVisible)(nil),                // 12: scraper.CA_WaitVisible
	(*CA_ScrollBy)(nil),                   // 13: scraper.CA_ScrollBy
}
var file_scraper_proto_depIdxs = []int32{
	2,  // 0: scraper.ControlRequest.emulateViewport:type_name -> scraper.CA_EmulateViewport
	3,  // 1: scraper.ControlRequest.navigate:type_name -> scraper.CA_Navigate
	4,  // 2: scraper.ControlRequest.sleep:type_name -> scraper.CA_Sleep
	5,  // 3: scraper.ControlRequest.click:type_name -> scraper.CA_Click
	6,  // 4: scraper.ControlRequest.sendKeys:type_name -> scraper.CA_SendKeys
	9,  // 5: scraper.ControlRequest.captureHtml:type_name -> scraper.CA_CaptureHtml
	7,  // 6: scraper.ControlRequest.captureScreenshot:type_name -> scraper.CA_CaptureScreenshot
	12, // 7: scraper.ControlRequest.waitVisible:type_name -> scraper.CA_WaitVisible
	13, // 8: scraper.ControlRequest.scrollBy:type_name -> scraper.CA_ScrollBy
	8,  // 9: scraper.ControlResponse.screenshot:type_name -> scraper.CA_CaptureScreenshot_Response
	10, // 10: scraper.ControlResponse.html:type_name -> scraper.CA_CaptureHtml_Response
	11, // 11: scraper.ControlResponse.error:type_name -> scraper.CA_Error_Response
	0,  // 12: scraper.Scraper.Control:input_type -> scraper.ControlRequest
	1,  // 13: scraper.Scraper.Control:output_type -> scraper.ControlResponse
	13, // [13:14] is the sub-list for method output_type
	12, // [12:13] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_scraper_proto_init() }
func file_scraper_proto_init() {
	if File_scraper_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_scraper_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ControlRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_scraper_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ControlResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_scraper_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CA_EmulateViewport); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_scraper_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CA_Navigate); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_scraper_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CA_Sleep); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_scraper_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CA_Click); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_scraper_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CA_SendKeys); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_scraper_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CA_CaptureScreenshot); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_scraper_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CA_CaptureScreenshot_Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_scraper_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CA_CaptureHtml); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_scraper_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CA_CaptureHtml_Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_scraper_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CA_Error_Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_scraper_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CA_WaitVisible); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_scraper_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CA_ScrollBy); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_scraper_proto_msgTypes[0].OneofWrappers = []interface{}{
		(*ControlRequest_EmulateViewport)(nil),
		(*ControlRequest_Navigate)(nil),
		(*ControlRequest_Sleep)(nil),
		(*ControlRequest_Click)(nil),
		(*ControlRequest_SendKeys)(nil),
		(*ControlRequest_CaptureHtml)(nil),
		(*ControlRequest_CaptureScreenshot)(nil),
		(*ControlRequest_WaitVisible)(nil),
		(*ControlRequest_ScrollBy)(nil),
	}
	file_scraper_proto_msgTypes[1].OneofWrappers = []interface{}{
		(*ControlResponse_Screenshot)(nil),
		(*ControlResponse_Html)(nil),
		(*ControlResponse_Error)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_scraper_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_scraper_proto_goTypes,
		DependencyIndexes: file_scraper_proto_depIdxs,
		MessageInfos:      file_scraper_proto_msgTypes,
	}.Build()
	File_scraper_proto = out.File
	file_scraper_proto_rawDesc = nil
	file_scraper_proto_goTypes = nil
	file_scraper_proto_depIdxs = nil
}
